using System;
using System.Collections.Generic;
using System.IO;
using Xunit;

namespace osu_trainer_avalonia.Tests
{
    // logo.ico is generated by tools/make-icons.py and committed. Its one silent-failure mode is
    // a regeneration that quietly drops a size: Windows would then upscale a neighbouring frame
    // and the tray icon would just look soft, with nothing failing. This reads the ICO directory
    // straight out of the file rather than through an image library, so a decoder that helpfully
    // synthesises missing sizes cannot hide the loss.
    public class IconAssetTests
    {
        private static readonly int[] ExpectedWidths = { 16, 24, 32, 48, 64, 128, 256 };

        [Fact]
        public void LogoIcoCarriesEverySizeTheAppAsksWindowsFor()
        {
            string path = Path.Combine(AppContext.BaseDirectory, "Assets", "logo.ico");
            Assert.True(File.Exists(path), $"missing generated asset: {path} (run tools/make-icons.py)");

            byte[] bytes = File.ReadAllBytes(path);

            // ICONDIR: reserved(2) = 0, type(2) = 1, count(2)
            Assert.Equal(0, BitConverter.ToUInt16(bytes, 0));
            Assert.Equal(1, BitConverter.ToUInt16(bytes, 2));
            int count = BitConverter.ToUInt16(bytes, 4);
            Assert.Equal(ExpectedWidths.Length, count);

            var widths = new List<int>();
            for (int i = 0; i < count; i++)
            {
                int entry = 6 + i * 16;                 // ICONDIRENTRY is 16 bytes
                int width = bytes[entry];               // 0 encodes 256
                widths.Add(width == 0 ? 256 : width);

                int byteLength = BitConverter.ToInt32(bytes, entry + 8);
                Assert.True(byteLength > 0, $"frame {i} ({widths[i]}px) declares zero bytes");
            }

            widths.Sort();
            Assert.Equal(ExpectedWidths, widths);
        }
    }
}
