<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OsuTrainerCore</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\osu-trainer\submodules\FsBeatmapParser\FsBeatmapProcessor.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="NAudio.Lame" Version="2.1.0" />
    <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="OsuMemoryDataProvider" Version="0.10.3" />
    <PackageReference Include="ProcessMemoryDataFinder" Version="0.8.5" />
  </ItemGroup>

</Project>
